import json
import datetime
import requests
from typing import List, Dict, Any, Optional
from pathlib import Path

try:
    import google.generativeai as genai
except ImportError:
    genai = None

from backend.config import (
    GEMINI_API_KEY, 
    GEMINI_CHAT_MODEL, 
    GEMINI_CONTENT_MODEL, 
    USER_NAME, 
    ASSISTANT_NAME, 
    CHATLOG_PATH, 
    GENERATED_CONTENT_PATH
)
from backend.weather_service import get_weather_by_city
from backend.os_service import open_file_in_notepad

class AIService:
    def __init__(self, api_key: str = GEMINI_API_KEY):
        self.api_key = api_key
        self.model = None
        self.content_model = None
        self._setup()

    def _setup(self):
        # Refresh key from config if empty
        if not self.api_key:
            from backend.config import GEMINI_API_KEY
            self.api_key = GEMINI_API_KEY

        if genai and self.api_key:
            try:
                genai.configure(api_key=self.api_key)
                system_instruction = (
                    f"Hello, I am {USER_NAME}. You are an accurate, advanced, and helpful AI assistant named {ASSISTANT_NAME}. "
                    "Provide responses in a professional, clear, concise, and structured tone using proper grammar."
                )
                self.model = genai.GenerativeModel(
                    model_name=GEMINI_CHAT_MODEL,
                    system_instruction=system_instruction
                )
                self.content_model = genai.GenerativeModel(
                    model_name=GEMINI_CONTENT_MODEL
                )
            except Exception as e:
                print(f"[AIService] Gemini SDK init info: {e}")
                self.model = None
                self.content_model = None

    def load_chat_history(self) -> List[Dict[str, str]]:
        """Load conversation history from JSON storage."""
        if CHATLOG_PATH.exists():
            try:
                with open(CHATLOG_PATH, "r", encoding="utf-8") as f:
                    return json.load(f)
            except (json.JSONDecodeError, IOError):
                return []
        return []

    def save_chat_history(self, messages: List[Dict[str, str]]):
        """Persist conversation history to JSON storage."""
        try:
            with open(CHATLOG_PATH, "w", encoding="utf-8") as f:
                json.dump(messages, f, indent=4)
        except IOError as e:
            print(f"[AIService] Error saving chat history: {e}")

    def get_realtime_context(self) -> str:
        """Construct current date/time context string for the LLM."""
        now = datetime.datetime.now()
        return (
            f"[Real-Time System Context: Day: {now.strftime('%A')}, Date: {now.strftime('%d %B %Y')}, Time: {now.strftime('%H:%M:%S')}]"
        )

    def clean_response(self, text: str) -> str:
        """Strip excess blank lines and system tags from generated text."""
        lines = text.split('\n')
        non_empty = [line.strip() for line in lines if line.strip()]
        return '\n'.join(non_empty).replace("</sys>", "")

    def _call_gemini_rest_api(self, contents: list, system_text: str, model_name: str = "gemini-1.5-pro") -> str:
        """Direct REST fallback for Gemini API that works with pure requests."""
        if not self.api_key:
            return "Gemini API key is not configured. Please set GEMINI_API_KEY in your .env file."

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model_name}:generateContent?key={self.api_key}"
        payload = {
            "contents": contents,
            "generationConfig": {
                "temperature": 0.7,
                "maxOutputTokens": 2048
            }
        }
        if system_text:
            payload["system_instruction"] = {
                "parts": [{"text": system_text}]
            }

        try:
            res = requests.post(url, json=payload, timeout=20)
            data = res.json()
            if res.status_code == 200:
                candidates = data.get("candidates", [])
                if candidates and "content" in candidates[0]:
                    parts = candidates[0]["content"].get("parts", [])
                    if parts and "text" in parts[0]:
                        return parts[0]["text"]
                return "No response generated by Gemini."
            else:
                error_msg = data.get("error", {}).get("message", res.text)
                return f"Gemini API Error ({res.status_code}): {error_msg}"
        except Exception as e:
            return f"Error connecting to Gemini API: {e}"

    def chat(self, prompt: str) -> str:
        """Send prompt to Google Gemini with context and conversation history."""
        history = self.load_chat_history()
        history.append({"role": "user", "content": prompt})

        # Inject real-time context (weather or date/time)
        if "weather" in prompt.lower() and " in " in prompt.lower():
            city = prompt.lower().split(" in ")[-1].strip()
            context_content = f"[Current Weather Context: {get_weather_by_city(city)}]"
        else:
            context_content = self.get_realtime_context()

        # Build contents structure from history
        contents = []
        for item in history[-8:-1]:
            role = "user" if item.get("role") == "user" else "model"
            content_text = item.get("content", "")
            if content_text:
                contents.append({"role": role, "parts": [{"text": content_text}]})

        full_user_prompt = f"{context_content}\n\n{prompt}"
        contents.append({"role": "user", "parts": [{"text": full_user_prompt}]})

        system_instruction = (
            f"Hello, I am {USER_NAME}. You are an accurate, advanced, and helpful AI assistant named {ASSISTANT_NAME}. "
            "Provide responses in a professional, clear, concise, and structured tone using proper grammar."
        )

        answer = ""
        # Try SDK first if configured
        if self.model:
            try:
                sdk_contents = []
                for c in contents:
                    sdk_contents.append({"role": c["role"], "parts": [c["parts"][0]["text"]]})
                response = self.model.generate_content(sdk_contents)
                answer = response.text if response and hasattr(response, 'text') else ""
            except Exception as e:
                print(f"[AIService] SDK call failed, trying REST API fallback: {e}")
                answer = ""

        # Fallback to direct REST API
        if not answer:
            answer = self._call_gemini_rest_api(contents, system_instruction, GEMINI_CHAT_MODEL)

        cleaned_answer = self.clean_response(answer)
        history.append({"role": "assistant", "content": cleaned_answer})
        self.save_chat_history(history)
        return cleaned_answer

    def generate_content(self, topic: str, auto_open: bool = True) -> str:
        """Generate formatted email/document content using Gemini and save to file."""
        prompt_instruction = (
            "You are a professional writing assistant. Draft high-quality, clearly structured, and formatted content "
            f"for the following topic:\n\n{topic}"
        )
        contents = [{"role": "user", "parts": [{"text": prompt_instruction}]}]

        result = ""
        if self.content_model:
            try:
                response = self.content_model.generate_content(prompt_instruction)
                result = response.text if response and hasattr(response, 'text') else ""
            except Exception:
                result = ""

        if not result:
            result = self._call_gemini_rest_api(contents, "", GEMINI_CONTENT_MODEL)

        cleaned = self.clean_response(result)

        # Save content to text file
        with open(GENERATED_CONTENT_PATH, "w", encoding="utf-8") as f:
            f.write(cleaned)

        if auto_open:
            open_file_in_notepad(str(GENERATED_CONTENT_PATH))

        return cleaned

# Global instance and module-level helper functions
default_ai_service = AIService()

def chat(prompt: str) -> str:
    return default_ai_service.chat(prompt)

def generate_content(topic: str, auto_open: bool = True) -> str:
    return default_ai_service.generate_content(topic, auto_open)
